In [9]:
import os
import numpy as np
import mne
import osl
import yaml
from scipy.io import savemat
import matplotlib.pyplot as plt

In [27]:
path = '/well/woolrich/projects/disp_csaky/reading_only_meeg/ryan/task_part2_rh_raw_tsss_mc.fif'
raw = mne.io.read_raw_fif(path, preload=True)

/tmp/ipykernel_28871/852112907.py:2: RuntimeWarning: This filename (/well/woolrich/projects/disp_csaky/reading_only_meeg/ryan/task_part2_rh_raw_tsss_mc.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  raw = mne.io.read_raw_fif(path, preload=True)


In [30]:
# find events
raw = raw.resample(100)

In [35]:
events = mne.find_events(raw, min_duration=0.002, shortest_event=1)

In [36]:
len(events)

1143

In [2]:
dataset_path = "/gpfs2/well/woolrich/projects/disp_csaky/CTF/13703/13703054_Lukas_20230511_reading-f.ds"
raw = mne.io.read_raw_ctf(dataset_path, preload=True)

ds directory : /gpfs2/well/woolrich/projects/disp_csaky/CTF/13703/13703054_Lukas_20230511_reading-f.ds
    res4 data read.
    hc data read.
    Separate EEG position data file not present.
    Quaternion matching (desired vs. transformed):
      -5.92   75.91    0.00 mm <->   -5.92   75.91    0.00 mm (orig :  -51.28   50.50 -269.87 mm) diff =    0.000 mm
       5.92  -75.91    0.00 mm <->    5.92  -75.91    0.00 mm (orig :   48.44  -63.44 -253.52 mm) diff =    0.000 mm
     118.81    0.00    0.00 mm <->  118.81    0.00    0.00 mm (orig :   72.39   55.73 -192.41 mm) diff =    0.000 mm
    Coordinate transformations established.
    Polhemus data for 3 HPI coils added
    Device coordinate locations for 3 HPI coils added
Picked positions of 64 EEG channels from channel info
    64 EEG locations added to Polhemus data.
    Measurement info composed.
Finding samples for /gpfs2/well/woolrich/projects/disp_csaky/CTF/13703/13703054_Lukas_20230511_reading-f.ds/13703054_Lukas_20230511_reading-

In [ ]:
ev = mne.events_from_annotations(raw)

In [ ]:
ev[0][:100]

In [ ]:
raw = raw.crop(tmin=100, tmax=120)

In [ ]:
%matplotlib widget
raw.plot(duration=20, n_channels=50)
e=0

In [ ]:
# print channel types
print(raw.get_channel_types())

In [3]:
raw.ch_names

['SCLK01-177',
 'BG1-4123',
 'BG2-4123',
 'BG3-4123',
 'BP1-4123',
 'BP2-4123',
 'BP3-4123',
 'BR1-4123',
 'BR2-4123',
 'BR3-4123',
 'G11-4123',
 'G12-4123',
 'G13-4123',
 'G22-4123',
 'G23-4123',
 'P11-4123',
 'P12-4123',
 'P13-4123',
 'P23-4123',
 'Q11-4123',
 'Q22-4123',
 'Q23-4123',
 'R11-4123',
 'R12-4123',
 'R13-4123',
 'R22-4123',
 'R23-4123',
 'MLC11-4123',
 'MLC12-4123',
 'MLC13-4123',
 'MLC14-4123',
 'MLC15-4123',
 'MLC16-4123',
 'MLC17-4123',
 'MLC21-4123',
 'MLC22-4123',
 'MLC23-4123',
 'MLC24-4123',
 'MLC25-4123',
 'MLC32-4123',
 'MLC41-4123',
 'MLC42-4123',
 'MLC51-4123',
 'MLC52-4123',
 'MLC53-4123',
 'MLC54-4123',
 'MLC55-4123',
 'MLC61-4123',
 'MLC62-4123',
 'MLC63-4123',
 'MLF11-4123',
 'MLF12-4123',
 'MLF13-4123',
 'MLF14-4123',
 'MLF21-4123',
 'MLF22-4123',
 'MLF23-4123',
 'MLF25-4123',
 'MLF31-4123',
 'MLF32-4123',
 'MLF33-4123',
 'MLF34-4123',
 'MLF35-4123',
 'MLF41-4123',
 'MLF42-4123',
 'MLF43-4123',
 'MLF44-4123',
 'MLF45-4123',
 'MLF46-4123',
 'MLF51-4123',
 '

In [4]:
config_text = """
meta:
    event_codes:
        words/hungry: 2
        words/tired: 3
        words/thirsty: 4
        words/toilet: 5
        words/pain: 6
preproc:
  - filter:         {l_freq: 1, h_freq: 25, method: 'iir', iir_params: {order: 5, ftype: butter}}
  - bad_channels:   {picks: 'grad'}
  - bad_segments:   {segment_len: 800, picks: 'grad'}
  - ica_raw:        {picks: 'meg', n_components: 64}
  - ica_autoreject: {picks: 'meg', ecgmethod: 'correlation', measure: 'correlation', threshold: 0.5}
  - find_events:    {min_duration: 0.002}
"""

In [ ]:
raw.ch_names

In [5]:
raw.set_channel_types({'UADC007-4123': 'eog',
                       'UADC008-4123': 'eog',
                       'UADC009-4123': 'ecg',})

<RawCTF | 13703054_Lukas_20230511_reading-f.meg4, 538 x 3512448 (2927.0 s), ~14.08 GB, data loaded>

In [8]:
osl_outdir = "/gpfs2/well/woolrich/projects/disp_csaky/CTF/13703/preproc25hz/oslpy"
config = yaml.load(config_text, Loader=yaml.FullLoader)
dataset = osl.preprocessing.run_proc_chain(config,
                                           dataset_path,
                                           outdir=osl_outdir,
                                           overwrite=True,
                                           gen_report=True)

13703054_Lukas_20230511_reading-f : OSL osl_logger: handler 'console' level set to 'INFO'
13703054_Lukas_20230511_reading-f : logging to file: /gpfs2/well/woolrich/projects/disp_csaky/CTF/13703/preproc25hz/oslpy/13703054_Lukas_20230511_reading-f/logs/13703054_Lukas_20230511_reading-f_preproc_raw.log
13703054_Lukas_20230511_reading-f : 2023-05-16 14:48:13 : Starting OSL Processing
13703054_Lukas_20230511_reading-f : input : /gpfs2/well/woolrich/projects/disp_csaky/CTF/13703/13703054_Lukas_20230511_reading-f.ds
13703054_Lukas_20230511_reading-f : IMPORTING: /gpfs2/well/woolrich/projects/disp_csaky/CTF/13703/13703054_Lukas_20230511_reading-f.ds
13703054_Lukas_20230511_reading-f : Detected CTF file format, using: mne.io.read_raw_ctf
13703054_Lukas_20230511_reading-f : MNE Stage - raw.filter
13703054_Lukas_20230511_reading-f : userargs: {'l_freq': 1, 'h_freq': 25, 'method': 'iir', 'iir_params': {'order': 5, 'ftype': 'butter'}}
13703054_Lukas_20230511_reading-f : OSL Stage - raw : detect_bad

KeyboardInterrupt: 

In [ ]:
raw = raw.pick(['mag'])

In [ ]:
raw._raw_times

In [ ]:
raw.info['time']

In [16]:
raw = raw.resample(100)

In [17]:
events = mne.events_from_annotations(raw)[0]

# only keep events with id below 7
events = events[events[:, -1] < 7]
print(events[:100])

Used Annotations descriptions: ['0', '1', '2', '3', '4', '5', '6', 'Btn1', 'Btn2', 'Btn3', 'Btn4', 'Tr0_1', 'Tr0_2', 'Tr0_3', 'Tr0_4', 'Tr0_5', 'Tr0_6', 'Tr0_7', 'Tr1_1', 'Tr1_2', 'Tr1_3', 'Tr1_4']
[[ 3609     0     5]
 [ 3703     0     1]
 [ 3806     0     3]
 [ 3893     0     1]
 [ 3983     0     6]
 [ 4065     0     1]
 [ 4163     0     2]
 [ 4261     0     1]
 [ 4356     0     4]
 [ 4446     0     1]
 [ 4551     0     2]
 [ 4635     0     1]
 [ 4724     0     5]
 [ 4816     0     1]
 [ 4913     0     4]
 [ 5006     0     1]
 [ 5113     0     6]
 [ 5193     0     1]
 [ 5285     0     3]
 [ 5372     0     1]
 [ 5815     0     4]
 [ 5895     0     1]
 [ 5993     0     3]
 [ 6075     0     1]
 [ 6180     0     2]
 [ 6278     0     1]
 [ 6368     0     5]
 [ 6453     0     1]
 [ 6550     0     6]
 [ 6648     0     1]
 [ 6746     0     2]
 [ 6845     0     1]
 [ 6948     0     3]
 [ 7028     0     1]
 [ 7133     0     4]
 [ 7217     0     1]
 [ 7310     0     6]
 [ 7390     0     1]
 [ 7

In [24]:
events[623:633]

array([[76898,     0,     1],
       [77000,     0,     6],
       [77000,     0,     6],
       [77085,     0,     1],
       [77176,     0,     4],
       [77275,     0,     1],
       [77378,     0,     3],
       [77478,     0,     1],
       [77568,     0,     4],
       [77660,     0,     1]])

In [18]:
times = [e[0] for e in events]

In [21]:
shifted = np.array(times[:-1]) - np.array(times[1:])

In [23]:
np.where(shifted == 0)

(array([624, 853]),)