In [57]:
import os
import numpy as np
import mne
import osl
import yaml
import torch
from sklearn.manifold import TSNE
from scipy.io import loadmat, savemat
import pandas as pd
import seaborn as sns
import pickle
from cichy_data import CichyData
import wavenets_classifier
import classifiers_linear
import matplotlib.pyplot as plt
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.decomposition import PCA

plt.rcParams['figure.figsize'] = [17, 12]

def diag_block_mat_slicing(L):
    shp = L[0].shape
    N = len(L)
    r = range(N)
    out = np.zeros((N,shp[0],N,shp[1]))
    out[r,:,r,:] = L
    return out.reshape(np.asarray(shp)*N)

In [2]:
data = np.random.rand(3, 4)
conv_w = np.random.rand(4, 2)

In [42]:
conv_w

array([[0.6444017 , 0.50092841],
       [0.88307439, 0.89638052],
       [0.83364766, 0.15539055],
       [0.66078684, 0.69615098]])

In [3]:
out = np.dot(data, conv_w)

In [4]:
out

array([[1.75768389, 1.24907767],
       [1.68313513, 1.15879695],
       [1.05770867, 0.4009219 ]])

In [5]:
out.reshape(-1)

array([1.75768389, 1.24907767, 1.68313513, 1.15879695, 1.05770867,
       0.4009219 ])

In [6]:
data

array([[0.34869715, 0.62419546, 0.71855802, 0.57923007],
       [0.57311546, 0.09268019, 0.70451951, 0.97558543],
       [0.1287344 , 0.05546846, 0.95258909, 0.19922545]])

In [7]:
data.reshape(-1)

array([0.34869715, 0.62419546, 0.71855802, 0.57923007, 0.57311546,
       0.09268019, 0.70451951, 0.97558543, 0.1287344 , 0.05546846,
       0.95258909, 0.19922545])

In [58]:
L = np.array([conv_w, conv_w, conv_w])
conv_w3 = diag_block_mat_slicing(L)

In [59]:
conv_w3

array([[0.6444017 , 0.50092841, 0.        , 0.        , 0.        ,
        0.        ],
       [0.88307439, 0.89638052, 0.        , 0.        , 0.        ,
        0.        ],
       [0.83364766, 0.15539055, 0.        , 0.        , 0.        ,
        0.        ],
       [0.66078684, 0.69615098, 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.6444017 , 0.50092841, 0.        ,
        0.        ],
       [0.        , 0.        , 0.88307439, 0.89638052, 0.        ,
        0.        ],
       [0.        , 0.        , 0.83364766, 0.15539055, 0.        ,
        0.        ],
       [0.        , 0.        , 0.66078684, 0.69615098, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.6444017 ,
        0.50092841],
       [0.        , 0.        , 0.        , 0.        , 0.88307439,
        0.89638052],
       [0.        , 0.        , 0.        , 0.        , 0.83364766,
        0.15539055],
       [0.        , 0

In [60]:
out2 = np.dot(data.reshape(-1), conv_w3)

In [61]:
out2

array([1.75768389, 1.24907767, 1.68313513, 1.15879695, 1.05770867,
       0.4009219 ])

In [63]:
(np.array(2)) * 3

6