In [1]:
import numpy as np
from collections import Counter
from scipy.io import savemat, loadmat

In [58]:
data = loadmat('rich_data/cch306.mat')
train_data = np.array(data['x_train'])[np.newaxis, :, :]
data = np.array(data['x_val'])[np.newaxis, :, :]

In [60]:
np.histogram(data[0, 0, :], bins=118)

(array([ 1475,  1351,  1379,  1410,  1382,  1379,  1405,  1387,  1444,
         1350,  1426,  1384,  1365,  1349,  1445,  1394,  1386,  1418,
         1409,  1394,  1384,  1420,  1445,  1413,  1400,  1352,  1445,
         1412,  1373,  1410,  1383,  1354,  1414,  1332,  1351,  1445,
         1394,  1412,  1352,  1384,  1413,  1362,  1374,  1434,  1382,
         1376,  1413,  1413,  1353,  1345,  1413,  1444,  1443,  1370,
         1405,  1448,  1386,  1474,  1381,  1436,  1382,  1429,  1381,
         1440,  1414,  1348,  1443,  1372,  1383,  1382,  1433,  1413,
         1348,  1417,  1383,  1382,  1410,  1399,  1414,  1361,  1377,
         1393,  1366,  1423,  1383,  1383,  1401,  1385,  1378,  1349,
         1474,  1445,  1413,  1382,  1414,  1381,  1389,  1413,  1384,
         1422,  1355,  1392,  1342,  1422,  1424,  1408,  1386,  1378,
         1383,  1403,  1474,  1432,  1376,  1443,  1350,  1405,  1444,
        95418]),
 array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.

In [59]:
sr = 256
inds = list(range(data.shape[2] - sr))

# how many timesteps needed to detect image
tresh = int(250 * 0.1)
back_tresh = int(0.5*250) - tresh

# loop over examples in batch
for i in inds:
    targets = data[0, -1, i:i+sr].copy()
    

    # if last timestep is one of the 118 images and enough time
    # has elapsed since image presentation
    if targets[-1] < 118 and targets[-tresh] == targets[-1]:
        data[0, -1, i] = targets[-1]
        s = 'first'

    # else predict last image presented
    else:
        unique, counts = np.unique(targets, return_counts=True)
        counts = counts[unique != 118]
        unique = unique[unique != 118]
        
        c = counts[np.argsort(counts)[-1]] if len(counts) else 0
        if c > back_tresh:
            data[0, -1, i] = unique[np.argsort(counts)[-1]]
            s = 'last'
        else:
            data[0, -1, i] = 118
            s = 'none'
        
    if not i%10000:
        print(s)
        print(targets)

# scale non-epoch class
nonepoch_trials = sum(data[0, -1, :] == 118)
epoch_trials = sum(data[0, -1, :] == 0)

print('Non-epoch trials: ', sum(data[0, -1, :] == 118))
print('Class 0  trials: ', sum(data[0, -1, :] == 0))
print('Class 1  trials: ', sum(data[0, -1, :] == 1))
print('Total trials: ', data.shape[2])

none
[118. 118. 118. 118. 118. 118. 118. 118. 118. 118. 118. 118. 118. 118.
 118. 118. 118. 118. 118. 118. 118. 118. 118. 118. 118. 118. 118. 118.
 118. 118. 118. 118. 118. 118. 118. 118. 118. 118. 118. 118. 118. 118.
 118. 118. 118. 118. 118. 118. 118. 118. 118. 118. 118. 118. 118. 118.
 118. 118. 118. 118. 118. 118. 118. 118. 118. 118. 118. 118. 118. 118.
 118. 118. 118. 118. 118. 118. 118. 118. 118. 118. 118. 118. 118. 118.
 118. 118. 118. 118. 118. 118. 118. 118. 118. 118. 118. 118. 118. 118.
 118. 118. 118. 118. 118. 118. 118. 118. 118. 118. 118. 118. 118. 118.
 118. 118. 118. 118. 118. 118. 118. 118. 118. 118. 118. 118. 118. 118.
 118. 118. 118. 118. 118. 118. 118. 118. 118. 118. 118. 118. 118. 118.
 118. 118. 118. 118. 118. 118. 118. 118. 118. 118. 118. 118. 118. 118.
 118. 118. 118. 118. 118. 118. 118. 118. 118. 118. 118. 118. 118. 118.
 118. 118. 118. 118. 118. 118. 118. 118. 118. 118. 118. 118. 118. 118.
 118. 118. 118. 118. 118. 118. 118. 118. 118. 118. 118. 118. 118. 118.
 

In [72]:
a = np.array([11, 11, 11, 11, 11, 11, 0, 0, 23, 23, 23])
a = np.append(0, a[1:])
b = a[1:] - a[:-1]
inds = np.where(a==23)

In [76]:
np.nonzero(a == 23)[0]

array([ 8,  9, 10])